package mx.edu.itson.alzheimerobregon.features.patient

/**
 * Data class representing a patient record stored in Firestore.
 *
 * This class is used as the domain model for patient-related operations and is
 * directly serialized/deserialized to/from Firestore documents using
 * Firestore's `toObject(...)` and `set(...)` methods.
 *
 * Implementation notes:
 * - Dates are represented as strings in this model (ISO-8601 format is recommended).
 *   Consider using a dedicated date type or a serialization adapter if you need
 *   stronger typing or validation.
 * - The repository layer is responsible for generating a document id when `id`
 *   is empty and for mapping between UI models and this persistence model if needed.
 *
 * @property id Firestore document id for the patient. When empty, a new id will be generated by the repository/service layer.
 * @property name Patient's given name.
 * @property lastName Patient's family name / surname.
 * @property birthDate Patient's date of birth as a string (preferably ISO-8601).
 * @property diagnosis Primary diagnosis for the patient (defaults to "Alzheimer").
 * @property admissionDate Date when the patient was admitted (string, preferably ISO-8601).
 */
data class Patient(
    val id: String = "", // Firestore document id; empty when creating a new patient
    val name: String = "", // Given name
    val lastName: String = "", // Family name / surname
    val birthDate: String = "", // Date of birth as ISO-8601 string (YYYY-MM-DD recommended)
    val diagnosis: String = "Alzheimer", // Primary diagnosis; defaults to "Alzheimer"
    val admissionDate: String = "" // Admission date as ISO-8601 string
)
