package mx.edu.itson.alzheimerobregon.features.patient

/**
 * Data class representing a patient record stored in Firestore.
 *
 * This class is used as the domain model for patient-related operations and is
 * directly serialized/deserialized to/from Firestore documents using
 * Firestore's `toObject(...)` and `set(...)` methods.
 *
 * Implementation notes:
 * - Dates are represented as strings in this model (ISO-8601 format is recommended).
 *   Consider using a dedicated date type or a serialization adapter if you need
 *   stronger typing or validation.
 * - The repository layer is responsible for generating a document id when `id`
 *   is empty and for mapping between UI models and this persistence model if needed.
 *
 * @property id Firestore document id for the patient. When empty, a new id will be generated by the repository/service layer.
 * @property name Patient's given name.
 * @property lastName Patient's family name / surname.
 * @property birthDate Patient's date of birth as a string (preferably ISO-8601).
 * @property diagnosis Primary diagnosis for the patient (defaults to "Alzheimer").
 * @property admissionDate Date when the patient was admitted (string, preferably ISO-8601).
 * @property medicalHistory A summary of the patient's medical history.
 * @property allergies A summary of the patient's known allergies.
 * @property medications A summary of the patient's current medications.
 * @property contactInfo A map containing contact information (e.g., phone, email) for the patient's primary contact person.
 * @property secondaryContactInfo A map containing contact information for a secondary contact person, if available.
 * @property roomNumber The hospital room number assigned to the patient.
 */

data class Patient(
    val id: String = "",
    val fullName: String = "",
    val age: Int = 0,
    val gender: String = "",
    val address: String = "",
    val primaryContact: Map<String, String> = emptyMap(),
    val secondaryContact: Map<String, String> = emptyMap(),
    val roomNumber: String = "",
    val admissionDate: String = "",
    val medicalHistory: String = "",
    val allergies: String = "",
    val medications: String = "",
    val diagnosis: String = "Alzheimer"
)